### ISSUE TITLE
[Aozan] qc: error while computing qc report for run

### ISSUE THREAD

**Issue by acheta7** [GenomicParisCentre/aozan#1]
Hi,  I have been trying to use the Aozan QC tool for about a week now.  With some effort I have created an Aozan config file for my BCL data directory and have completed the BCL to FASTQ conversion step successfully (no reported errors at least) using Aozan. 

I now run into the following error in the QC report step which I cannot resolve:

Subject: [Aozan] qc: error while computing qc report for run
 150416_E00247_0108_AH3YYHCCXX.
Date: Fri, 06 May 2016 21:17:19 -0000

THIS IS AN AUTOMATED MESSAGE.

java.lang.NullPointerException: None
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:514)
        at java.util.Properties.setProperty(Properties.java:161)
        at fr.ens.biologie.genomique.eoulsan.Settings.setGenomeDescStoragePath(Settings.java:868)
        at fr.ens.biologie.genomique.aozan.QC.initGenomeDescriptionCreator(QC.java:688)
        at fr.ens.biologie.genomique.aozan.QC.<init>(QC.java:871)
        at fr.ens.biologie.genomique.aozan.QC.<init>(QC.java:837)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)
        at org.python.core.PyReflectedConstructor.**call**(PyReflectedConstructor.java:180)
        at org.python.core.PyObject.**call**(PyObject.java:419)
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
        at org.python.core.PyMethod.**call**(PyMethod.java:228)

Can you please assist with resolving this error?

Thanks,
Cooper Roddey

**Comment by acheta7** [comment]
The Aozan version I am using:  aozan-2.0-rc14-SNAPSHOT
